name: Close stale issues and PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *' # Everyday at 01:30

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/stale@v8
          with:
            stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within the next 5 days. If you believe this issue is still relevant, please comment to keep it open. Thank you for your contributions.'
            stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within the next 30 days. If you believe this PR is still relevant, please comment to keep it open. Thank you for your contributions.'
            days-before-stale: 30
            days-before-issue-close: 5
            days-before-pr-close: 30